package com.moon.quizcat

class Const {
    val thumbnail = arrayOf(
        R.drawable.americancurl,
        R.drawable.americanshorthair,
        R.drawable.americanwirehair,
        R.drawable.avinisian,
        R.drawable.baliniz,
        R.drawable.bombay,
        R.drawable.britishshorthair,
        R.drawable.cellkurkrex,
        R.drawable.conishirex,
        R.drawable.corat,
        R.drawable.debonrex,
        R.drawable.egysionmow,
        R.drawable.europeanshorthair,
        R.drawable.exjoticshorthair,
        R.drawable.havanabrown,
        R.drawable.hymalayan,
        R.drawable.japanesebobtail,
        R.drawable.kimric,
        R.drawable.maincun,
        R.drawable.mancs,
        R.drawable.munchiken,
        R.drawable.nebelrung,
        R.drawable.norwayforest,
        R.drawable.orientallonghair,
        R.drawable.orientalshorthair,
        R.drawable.osicat,
        R.drawable.perssian,
        R.drawable.peterbald,
        R.drawable.pixibob,
        R.drawable.ragamuffin,
        R.drawable.ragdol,
        R.drawable.rapham,
        R.drawable.russianblue,
        R.drawable.savana,
        R.drawable.scotishifold,
        R.drawable.shartrey,
        R.drawable.siam,
        R.drawable.siberian,
        R.drawable.singapura,
        R.drawable.snowshu,
        R.drawable.somali,
        R.drawable.spinkx,
        R.drawable.taicat,
        R.drawable.tonkinese,
        R.drawable.toyger,
        R.drawable.turkeyshiangora,
        R.drawable.van,
        R.drawable.vengol,
        R.drawable.verma,
        R.drawable.verman,
        R.drawable.vermilla
    )

    val name = arrayOf(
        "아메리칸 컬",
        "아메리칸 숏 헤어",
        "아메리칸 롱 헤어",
        "아비시니안",
        "발리니즈",
        "봄베이",
        "브리티쉬 숏 헤어",
        "셀커크 렉스",
        "코니시 렉스",
        "코랏",
        "데본 렉스",
        "이집션 마우",
        "유러피안 숏 헤어",
        "엑조틱 숏 헤어",
        "하바나 브라운",
        "히말라얀",
        "재패니즈 밥 테일",
        "킴 릭",
        "메인쿤",
        "맹크스",
        "먼치킨",
        "네벨룽",
        "노르웨이 숲",
        "오리엔탈 롱 헤어",
        "오리엔탈 숏 헤어",
        "오시캣",
        "페르시안",
        "피터볼드",
        "픽시 밥",
        "라가 머핀",
        "래그돌",
        "라팜",
        "러시안 블루",
        "사바나",
        "스코티시 폴드",
        "샤르트뢰",
        "시암",
        "시베리안",
        "싱가푸라",
        "스노우슈",
        "소말리",
        "스핑크스",
        "타이캣",
        "톤키니즈",
        "토이거",
        "터키시 앙고라",
        "반",
        "벵골",
        "버마",
        "버먼",
        "버밀라"
    )
}